name: Release

on: [push, workflow_dispatch]

jobs:
  create-image:
    if: github.event.pull_request.draft != true  # #GreenIT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: LinqLover/create-image@latest
        id: create-image
        with:
          squeak-version: trunk
          prepare-script: ./scripts/prepareImage.st
          postpare-script: ./scripts/postpareImage.st
      - uses: actions/upload-artifact@master
        with:
          name: image
          path: ${{ steps.create-image.outputs.bundle-path }}
  release-image:
    needs: create-image
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - id: date
        run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@master
        with:
          name: image
      - run: mv Squeak*.zip SqueakInboxTalk-${{ steps.date.outputs.date }}.zip
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: untagged-${{ steps.date.outputs.date }}
          body: ${{ github.event.head_commit.message }}
          files: SqueakInboxTalk-*.zip
          fail_on_unmatched_files: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          delete_tag_pattern: untagged-
          keep_latest: 1
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
