name: Release

on: [push, workflow_dispatch]

jobs:
  create-image:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: smalltalkci
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: Squeak64-Trunk
      - run: ./scripts/create_image.sh
  release-image:
    needs: create-image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - run: mv {Squeak*,SqueakInboxTalk-${{ steps.short-sha.outputs.sha }}}.zip
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: untagged-${{ steps.short-sha.outputs.sha }}
          body: ${{ github.event.head_commit.message }}
          files: SqueakInboxTalk-${{ steps.short-sha.outputs.sha }}.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
