name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: smalltalkci
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: Squeak64-Trunk
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }}
        timeout-minutes: 15
        env:
          # for uploading coverage reports
          GITHUB_TOKEN: ${{ github.token }}
          SIT_GIST_TOKEN: ${{ secrets.SIT_GIST_TOKEN }}
  release:
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - run: ./scripts/prepare_image.sh
      - run: mv {Squeak*,SqueakInboxTalk-${{ steps.short-sha.outputs.sha }}}.zip
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: untagged-${{ steps.short-sha.outputs.sha }}
          body: ${{ github.event.head_commit.message }}
          files: SqueakInboxTalk-${{ steps.short-sha.outputs.sha }}.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
