name: Tests

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: smalltalkci
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: Squeak64-6.0
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }}
        timeout-minutes: 15
        env:
          # for uploading coverage reports
          GITHUB_TOKEN: ${{ github.token }}
          SIT_GIST_TOKEN: ${{ secrets.SIT_GIST_TOKEN }}
